# Linear Algebra

In [1]:
import numpy.linalg as la
import scipy.sparse as sp
import numpy as np

In [2]:
np.set_printoptions(precision=3,suppress=True)

In [3]:
A = np.matrix(np.random.randint(5, size = (3,3)))

In [4]:
A

matrix([[0, 3, 3],
        [2, 3, 1],
        [0, 4, 3]])

In [5]:
np.asmatrix(([1,2,3],[4,5,6]))

matrix([[1, 2, 3],
        [4, 5, 6]])

In [6]:
np.mat(([1,2,3]))

matrix([[1, 2, 3]])

---

Inverse : The inverse of matrix is another matrix, which on multiplying with the given matrix gives the multiplicative identity.

In [7]:
A.I

matrix([[ 0.833,  0.5  , -1.   ],
        [-1.   ,  0.   ,  1.   ],
        [ 1.333,  0.   , -1.   ]])

In [8]:
# To verify, @: Matrix Multiplication
A.I @ A

matrix([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [9]:
# A = 
0.5*(A - A.T) + 0.5*(A + A.T) 

matrix([[0., 3., 3.],
        [2., 3., 1.],
        [0., 4., 3.]])

The trace of a square matrix A, denoted tr, is defined to be the sum of elements on the main diagonal of A. 

In [10]:
np.trace(A)

6

A **norm** of a vector $||x||$ is informally a measure of the “length” of the vector. $$ \lVert x \rVert = \sqrt{x^T x} $$

In [12]:
la.norm(np.array([3,4]))

5.0

In [19]:
((np.array([3,4])).T @ (np.array([3,4])))**0.5

5.0

The **inner product**
$$ x^T y = \sum_i x_i y_i $$
of vectors (or columns of a matrix) tell us about the **magnitude** and about the **angle** formed by the two vectors. Think about it this way: the magnitude, or **norm**, of a vector tells the mountain climber how far she is from her starting point (origin). The **angle** between two vectors tells someone at the origin what the viewing angle is between one climber (one vector), and the other climber (the other vector).

Inner products are **bilinear**, which means that they satisfy some convenient algebraic properties

$$ \begin{split}
(x + y)^T z &= x^T z + y^T z \\
x^T (y + z) &= x^T y + x^T z \\
(\alpha x)^T (\beta y) &= \alpha \beta x^T y \\
\end{split}  $$

***Orthogonal***: If  𝑥𝑇𝑦=0  then we say  𝑥  and  𝑦  are orthogonal (or " 𝑥  is orthogonal to  𝑦 "). The cosine of the angle between the two vectors is 0, which means the angle formed by the two vectors is a 90 degree angle

In [37]:
vector_1 = [0, 1]
vector_2 = [1, 0]

#Normalizing the vectors to find the unit vectors. Not necessary
unit_vector_1 = vector_1 / la.norm(vector_1)
unit_vector_2 = vector_2 / la.norm(vector_2)
dot_product = np.dot(unit_vector_1, unit_vector_2)

print("In radians:", np.arccos(dot_product))
print("In degrees", np.degrees(np.arccos(dot_product)))

print("Hence, Orthogonal")

In radians: 1.5707963267948966
In degrees 90.0
Hence, Orthogonal


In [38]:
np.degrees(np.arccos(np.array(vector_1) @ np.array(vector_2)))

90.0

If $x$ is orthogonal to $y$ and $\lVert x \rVert = \lVert y \rVert = 1$ then we say $x$ and $y$ are **orthonormal**.

In 2D, there are 4 cardinal points, forming two directional axes. In $n$D, there are $2n$ cardinal points forming $n$ directional axes.

A square matrix with **orthonormal** column vectors is said to be an **orthogonal matrix**. In $n$ dimensions, Together, they form an $n$-dimensional *unit* **hypercube**.

We typically use $Q$ or $U$ and $V$ for matrices that are known/constructed to be orthogonal.
Orthogonal matrices are always full rank -- the columns are **linearly independent**. That means no one column can be written as a linear combination of any of the other ones.

The inverse of an **orthogonal** matrix is its **transpose**:
$$ Q^T = I . $$

That's nice because transposing a matrix is super easy. Finding the inverse of a non-orthogonal matrix is **hard**. The runtime complexity is bounded by $O(n^3)$. 

In [59]:
U = (0.5**0.5) * np.mat(([1,1],[1,-1])) # Sample Orthogonal Matrix
U

matrix([[ 0.707,  0.707],
        [ 0.707, -0.707]])

In [60]:
U.T

matrix([[ 0.707,  0.707],
        [ 0.707, -0.707]])

In [61]:
U.I

matrix([[ 0.707,  0.707],
        [ 0.707, -0.707]])

In [70]:
np.allclose(U.T,U.I)

True

**Rank***: The rank of the matrix refers to the number of linearly independent rows or columns in the matrix.


In [13]:
A = np.mat(([1,0,1],[14,5,6],[7,8,9]))
A

matrix([[ 1,  0,  1],
        [14,  5,  6],
        [ 7,  8,  9]])

In [14]:
la.matrix_rank(A)

3

In [15]:
B = np.mat(([1,2,3],[1,2,3],[1,2,3]))

In [16]:
la.matrix_rank(B)

1

The determinant is a scalar value that is a function of the entries of a square matrix.

In [17]:
la.det(A)

74.00000000000003

Solving a system of linear equations

$$ A x = b$$

In [66]:
C = np.array([[20, 11, 11],[9, 4, 9], [11, 7, 5]])

z = np.array([33, 22, 17])

solution = np.linalg.solve(C, z)
solution

array([-0.,  1.,  2.])

In [67]:
C @ solution

array([33., 22., 17.])

In [69]:
Cinv = np.linalg.inv(C)
print(Cinv @ C)
print('---')
print()
print(C @ Cinv)
print('---')
print()
print(np.allclose(np.linalg.solve(C, C), (np.eye(3,3))))
print('---')

[[ 1.  0.  0.]
 [-0.  1. -0.]
 [-0.  0.  1.]]
---

[[ 1.  0. -0.]
 [ 0.  1. -0.]
 [ 0.  0.  1.]]
---

True
---
