# Linear Algebra

In [32]:
import numpy.linalg as la
import numpy as np`

In [53]:
np.set_printoptions(precision=3,suppress=True)

---

### Initializing a np array

In [52]:
np.random.rand(3,3)

array([[0.081, 0.726, 0.817],
       [0.342, 0.864, 0.55 ],
       [0.368, 0.44 , 0.908]])

In [87]:
np.array([(1,2,3),(4,5,6)])

array([[1, 2, 3],
       [4, 5, 6]])

In [77]:
np.array([1,2,3])

array([1, 2, 3])

Identity Matrix

In [38]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [106]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [101]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

An array of evenly spaced values (number of samples)

In [103]:
np.linspace(0,2,9) 

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

Zero Matrix

In [81]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [99]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

np.empty , unlike zeros , does not set the array values to zero, and may therefore be marginally faster. On the other hand, it requires the user to manually set all the values in the array, and should be used with caution.

In [105]:
np.full((2,4),7) 

array([[7, 7, 7, 7],
       [7, 7, 7, 7]])

---

Number of dimensions, shape (length of each dimension) and size (number of all elements) of NumPy array

In [92]:
np.array([1,2,3]).shape

(3,)

In [94]:
np.array([(1,2,3),(4,5,6)]).shape

(2, 3)

In [96]:
np.array([(1,2,3),(4,5,6)]).ndim

2

In [97]:
len(np.array([(1,2,3),(4,5,6)]))

2

---

Transpose

In [72]:
x = np.random.randint(10, size = (3,3))
x

array([[4, 6, 2],
       [6, 2, 6],
       [7, 3, 6]])

In [49]:
x.T

array([[2, 6, 4],
       [4, 9, 9],
       [0, 8, 8]])

Scalar Multiplication

In [39]:
3 * np.identity(3)

array([[3., 0., 0.],
       [0., 3., 0.],
       [0., 0., 3.]])

In [61]:
x = np.random.randint(10, size = (3,3))
x

array([[2, 3, 5],
       [9, 2, 8],
       [3, 8, 5]])