# Linear Algebra

In [85]:
import numpy.linalg as la
import scipy.sparse as sp
import numpy as np
import math

In [2]:
np.set_printoptions(precision=3,suppress=True)

In [3]:
A = np.matrix(np.random.randint(5, size = (3,3)))

In [4]:
A

matrix([[0, 3, 3],
        [2, 3, 1],
        [0, 4, 3]])

In [5]:
np.asmatrix(([1,2,3],[4,5,6]))

matrix([[1, 2, 3],
        [4, 5, 6]])

In [6]:
np.mat(([1,2,3]))

matrix([[1, 2, 3]])

---

Inverse : The inverse of matrix is another matrix, which on multiplying with the given matrix gives the multiplicative identity.

In [7]:
A.I

matrix([[ 0.833,  0.5  , -1.   ],
        [-1.   ,  0.   ,  1.   ],
        [ 1.333,  0.   , -1.   ]])

In [8]:
# To verify, @: Matrix Multiplication
A.I @ A

matrix([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [9]:
# A = 
0.5*(A - A.T) + 0.5*(A + A.T) 

matrix([[0., 3., 3.],
        [2., 3., 1.],
        [0., 4., 3.]])

Cosine rule

$|r - s|^2 = |r|^2 + |s|^2 + 2|r||s|\cos\theta$ 

In [102]:
r = np.array([0, 1])
s = np.array([1, 0])

print(la.norm(r - s) ** 2)
print(la.norm(r) ** 2 +  la.norm(s) ** 2)
print( (2*la.norm(r)*la.norm(s)*math.cos(np.arccos(r@s))).round(3))


print("For Ref: Degrees", np.degrees(np.arccos(r@s)))

2.0000000000000004
2.0
0.0
For Ref: Degrees 90.0


In [103]:
(r-s)@(r-s)

2

In [90]:
math.cos(90)

-0.4480736161291701

The trace of a square matrix A, denoted tr, is defined to be the sum of elements on the main diagonal of A. 

In [10]:
np.trace(A)

6

A **norm** of a vector $||x||$ is informally a measure of the “length” of the vector. $$ \lVert x \rVert = \sqrt{x^T x} $$

In [12]:
la.norm(np.array([3,4]))

5.0

In [19]:
((np.array([3,4])).T @ (np.array([3,4])))**0.5

5.0

The **inner product**
$$ x^T y = \sum_i x_i y_i $$
of vectors (or columns of a matrix) tell us about the **magnitude** and about the **angle** formed by the two vectors. Think about it this way: the magnitude, or **norm**, of a vector tells the mountain climber how far she is from her starting point (origin). T

Inner products are **bilinear**, which means that they satisfy some convenient algebraic properties

$$ \begin{split}
(x + y)^T z &= x^T z + y^T z \\
x^T (y + z) &= x^T y + x^T z \\
(\alpha x)^T (\beta y) &= \alpha \beta x^T y \\
\end{split}  $$

***Orthogonal***: If  𝑥𝑇𝑦=0  then we say  𝑥  and  𝑦  are orthogonal (or " 𝑥  is orthogonal to  𝑦 "). The cosine of the angle between the two vectors is 0, which means the angle formed by the two vectors is a 90 degree angle

In [167]:
vector_1 = [0, 1]
vector_2 = [1, 0]

#Normalizing the vectors to find the unit vectors. Not necessary
unit_vector_1 = vector_1 / la.norm(vector_1)
unit_vector_2 = vector_2 / la.norm(vector_2)
dot_product = np.dot(unit_vector_1, unit_vector_2)

print("In radians:", np.arccos(dot_product))
print("In degrees", np.degrees(np.arccos(dot_product)))

print("Hence, Orthogonal")

In radians: 1.5707963267948966
In degrees 90.0
Hence, Orthogonal


In [168]:
np.degrees(np.arccos(np.array(vector_1) @ np.array(vector_2)))

90.0

If $x$ is orthogonal to $y$ and $\lVert x \rVert = \lVert y \rVert = 1$ then we say $x$ and $y$ are **orthonormal**.

In 2D, there are 4 cardinal points, forming two directional axes. In $n$D, there are $2n$ cardinal points forming $n$ directional axes.

A square matrix with **orthonormal** column vectors is said to be an **orthogonal matrix**. In $n$ dimensions, Together, they form an $n$-dimensional *unit* **hypercube**.

We typically use $Q$ or $U$ and $V$ for matrices that are known/constructed to be orthogonal.
Orthogonal matrices are always full rank -- the columns are **linearly independent**. That means no one column can be written as a linear combination of any of the other ones.

The inverse of an **orthogonal** matrix is its **transpose**:
$$ Q^T = I . $$

That's nice because transposing a matrix is super easy. Finding the inverse of a non-orthogonal matrix is **hard**. The runtime complexity is bounded by $O(n^3)$. 

In [59]:
U = (0.5**0.5) * np.mat(([1,1],[1,-1])) # Sample Orthogonal Matrix
U

matrix([[ 0.707,  0.707],
        [ 0.707, -0.707]])

In [60]:
U.T

matrix([[ 0.707,  0.707],
        [ 0.707, -0.707]])

In [61]:
U.I

matrix([[ 0.707,  0.707],
        [ 0.707, -0.707]])

In [70]:
np.allclose(U.T,U.I)

True

**Rank***: The rank of the matrix refers to the number of linearly independent rows or columns in the matrix.


In [13]:
A = np.mat(([1,0,1],[14,5,6],[7,8,9]))
A

matrix([[ 1,  0,  1],
        [14,  5,  6],
        [ 7,  8,  9]])

In [14]:
la.matrix_rank(A)

3

In [15]:
B = np.mat(([1,2,3],[1,2,3],[1,2,3]))

In [16]:
la.matrix_rank(B)

1

The determinant is a scalar value that is a function of the entries of a square matrix.

In [17]:
la.det(A)

74.00000000000003

---

## Solving a system of linear equations

$$ A x = b$$

In [127]:
A = np.array(([2,10],[3,1]))
s = np.array([8,13])

print(np.linalg.solve(A, s))

np.linalg.inv(A) @ s


[ 4.357 -0.071]


array([ 4.357, -0.071])

### Gaussian elimination

In [155]:
A = np.array(([1,1,3],[1,2,4],[1,1,2]))
s = np.array([15,21,13])

In [156]:
A[2] = A[2] - A[0]
s[2] = s[2] - s[0]

In [157]:
print(A)
print(s.T)

[[ 1  1  3]
 [ 1  2  4]
 [ 0  0 -1]]
[15 21 -2]


In [158]:
A[2] = A[2]* -1
s[2] = s[2]* - 1

In [159]:
print(A)
print(s.T)

[[1 1 3]
 [1 2 4]
 [0 0 1]]
[15 21  2]


In [160]:
A[1] = A[1] - A[0]
s[1] = s[1] - s[0]

In [161]:
print(A)
print(s)

[[1 1 3]
 [0 1 1]
 [0 0 1]]
[15  6  2]


A is in the echelon form. Now, solve by back substitution

In [162]:
A[1] = A[1] - A[2]
s[1] = s[1] - s[2]

In [163]:
print(A)
print(s)

[[1 1 3]
 [0 1 0]
 [0 0 1]]
[15  4  2]


In [164]:
A[0] = A[0] - 3 * A[2] - A[1]
s[0] = s[0] - 3 * s[2] - s[1]

In [165]:
print(A)
print(s)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[5 4 2]


In [166]:
print(np.linalg.solve(A, s))


[5. 4. 2.]


---
<div style="text-align: right; color: gray">6</div>

## Eigenvalues and eigenvectors

>**Definition**: A scalar $\lambda$ is an **eigenvalue** for the linear map A (A is the matrix of the linear map) if there exists a non-zero vector $V$ such that $Av = \lambda v$. Any such vector which satisfies this equation is said to be an **eigenvector** of A, corresponding to the eigenvalue $\lambda$.

Eigenvectors and eigenvalues have a huge number of [applications](http://en.wikipedia.org/wiki/Eigenvalues_and_eigenvectors#Applications), including facial recognition
software, geology, quantum mechanics, and web search. So being able to find them quickly is of great significance to researchers and engineers. What’s interesting is that while eigenvectors depend on a choice of basis, eigenvalues do not.

### Again: What is an eigenvector?

* A Matrix is a mathematical object that acts on a (column) vector, resulting in a new vector, i.e. A**x**=**b**. It represents a **move**, in any direction, for a mountain-climber, such as Tomb Raider.

* A vector is like an arrow pointing to a location on the mountain. An **eigenvector** $v$ is a **position on the mountain** $x$ such that ***for a class of mountain moves described by a matrix $C$***, the resulting position (or vector) $y$ following that mountain move is **parallel** to the original position $x$ (some multiple of $x$). 

It's as if the **new position** of the mountain climber is **in the same direction** as defined by her previous position and the origin (where she started her climb):

$$ {C}\underline{x}=\lambda \underline{x} $$

$\lambda$ is its **eigenvalue**. It's **how much** the mountain climber moved from the previous position.


### Again: What are eigenvalues?

Given $A \in \mathbb{R}^{n\times n}$, $\lambda$ is the **eigenvalue** of $C$ if there is a non-zero vector $x$, the corresponding **eigenvector**, such that the following is true:

$$Cx = \lambda x, \;\; \text{for} \; x \neq 0$$

Is there a move that can take a mountain-climber to *some factor* times her original position? If so, the old position is an eigenvector, and the moving factor is its eigenvalue.

Formally, given a square matrix $C \in \mathbb{R}^{n\times n}$, we say that $\lambda \in \mathbb{C}$ is an **eigenvalue** of $C$ and $x \in \mathbb{C}^n$ is the corresponding **eigenvector**.

Intuitively, this definition means that multiplying $C$ by the vector $x$ results in a new vector that points in the same direction as $x$, but is scaled by a factor $\lambda$.

Also note that for any **eigenvector** $x \in \mathbb{C}^n$ **of $C$**, and scalar $k \in \mathbb{C}, C(kx) = kCx = k\lambda x = \lambda(kx)$, so $kx$ is also an **eigenvector of $C$**. For this reason when we talk about **“the” eigenvector** associated with $\lambda$, we usually assume that the **eigenvector** is normalized to have length $1$ (this still creates some ambiguity, since $x$ and $−x$ will both be **eigenvectors**, but we will have to live with this).

For any $\lambda$ an eigenvalue of $C$, there is a vector space, the **eigenspace**, that corresponds to $\lambda$:

$$\{ x : C x = \lambda x \}$$

Any non-zero vector in this space is an eigenvector. One convenient requirement is that the eigenvector has norm $1$.

