# Numpy

In [1]:
import numpy.linalg as la
import numpy as np

In [2]:
np.set_printoptions(precision=3,suppress=True)

---

### Initializing a np array

In [3]:
np.random.rand(3,3)

array([[0.434, 0.156, 0.709],
       [0.346, 0.723, 0.139],
       [0.353, 0.127, 0.224]])

In [4]:
np.random.randint(10, size = (3,3))


array([[6, 3, 5],
       [0, 2, 5],
       [1, 3, 8]])

In [5]:
np.array([(1,2,3),(4,5,6)])

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
np.array([1,2,3])

array([1, 2, 3])

Identity Matrix

In [7]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [9]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

An array of evenly spaced values (number of samples)

In [10]:
np.linspace(0,2,9) 

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

Zero Matrix

In [11]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.empty((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

np.empty , unlike zeros , does not set the array values to zero, and may therefore be marginally faster. On the other hand, it requires the user to manually set all the values in the array, and should be used with caution.

In [13]:
np.full((2,4),7) 

array([[7, 7, 7, 7],
       [7, 7, 7, 7]])

---

### Inspecting Your Array

In [14]:
np.array([1,2,3]).shape

(3,)

In [15]:
np.array([(1,2,3),(4,5,6)]).shape

(2, 3)

In [16]:
np.array([(1,2,3),(4,5,6)]).ndim

2

In [17]:
len(np.array([(1,2,3),(4,5,6)]))

2

In [18]:
np.array([(1,2,3),(4,5,6)]).dtype

dtype('int64')

In [19]:
np.array([(1,2,3),(4,5,6)]).dtype.name

'int64'

In [20]:
np.info(np.array([(1,2,3),(4,5,6)]))

class:  ndarray
shape:  (2, 3)
strides:  (24, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x7fd49c4626b0
byteorder:  little
byteswap:  False
type: int64


In [21]:
x = np.random.rand(3,3)
print(x)
print()
print(x.astype(int))

[[0.971 0.024 0.965]
 [0.565 0.744 0.967]
 [0.494 0.431 0.036]]

[[0 0 0]
 [0 0 0]
 [0 0 0]]


---

### Matrix Manipulations

Transpose

In [22]:
np.transpose(x)

array([[0.971, 0.565, 0.494],
       [0.024, 0.744, 0.431],
       [0.965, 0.967, 0.036]])

In [23]:
x.T

array([[0.971, 0.565, 0.494],
       [0.024, 0.744, 0.431],
       [0.965, 0.967, 0.036]])

Scalar Multiplication

In [24]:
3 * np.identity(3)

array([[3., 0., 0.],
       [0., 3., 0.],
       [0., 0., 3.]])

In [25]:
x.ravel()

array([0.971, 0.024, 0.965, 0.565, 0.744, 0.967, 0.494, 0.431, 0.036])

In [26]:
x.reshape(3,3) # Transpose

array([[0.971, 0.024, 0.965],
       [0.565, 0.744, 0.967],
       [0.494, 0.431, 0.036]])

In [27]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [28]:
a.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [29]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [30]:
a = a.reshape(3,2)
b = np.array([(6,7),(8,9)])

In [31]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [32]:
b

array([[6, 7],
       [8, 9]])

In [33]:
np.concatenate((a,b)) # Add a tuple

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [34]:
np.vstack((a,b))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [35]:
# np.hstack((a,b))

---

### Matrix Operations

In [36]:
x = np.random.randint(1,10, size = (3,3))
x

array([[7, 7, 1],
       [8, 8, 9],
       [5, 5, 2]])

In [37]:
y = np.random.randint(1,10, size = (3,3))
y

array([[1, 6, 2],
       [1, 1, 1],
       [3, 6, 4]])

In [38]:
np.add(x,y)

array([[ 8, 13,  3],
       [ 9,  9, 10],
       [ 8, 11,  6]])

In [39]:
x + y

array([[ 8, 13,  3],
       [ 9,  9, 10],
       [ 8, 11,  6]])

In [40]:
np.subtract(x,y)

array([[ 6,  1, -1],
       [ 7,  7,  8],
       [ 2, -1, -2]])

In [41]:
x - y

array([[ 6,  1, -1],
       [ 7,  7,  8],
       [ 2, -1, -2]])

In [42]:
np.divide(x,y) #Element-wise

array([[7.   , 1.167, 0.5  ],
       [8.   , 8.   , 9.   ],
       [1.667, 0.833, 0.5  ]])

In [43]:
x/y

array([[7.   , 1.167, 0.5  ],
       [8.   , 8.   , 9.   ],
       [1.667, 0.833, 0.5  ]])

In [44]:
np.multiply(x,y) #Element-wise

array([[ 7, 42,  2],
       [ 8,  8,  9],
       [15, 30,  8]])

In [45]:
np.exp([1,2,3]) # Natural(e)

array([ 2.718,  7.389, 20.086])

In [46]:
2.718 ** 1, 2.718 ** 2, 2.718 ** 3 

(2.718, 7.387524, 20.079290231999998)

In [47]:
np.sqrt(x)

array([[2.646, 2.646, 1.   ],
       [2.828, 2.828, 3.   ],
       [2.236, 2.236, 1.414]])

In [48]:
np.sin(x)

array([[ 0.657,  0.657,  0.841],
       [ 0.989,  0.989,  0.412],
       [-0.959, -0.959,  0.909]])

In [49]:
np.log(x) # Element-wise natural logarithm

array([[1.946, 1.946, 0.   ],
       [2.079, 2.079, 2.197],
       [1.609, 1.609, 0.693]])

*** * ****
### Dot Product

In [50]:
x.dot(y)

array([[ 17,  55,  25],
       [ 43, 110,  60],
       [ 16,  47,  23]])

---

### Comparisons

In [51]:
x == y

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [52]:
x < y

array([[False, False,  True],
       [False, False, False],
       [False,  True,  True]])

In [53]:
np.array_equal(x, y) 

False

---

### Aggregate Functions

In [54]:
x.sum()

52

In [55]:
x.min()

1

In [56]:
x.max()

9

In [57]:
x.max(axis = 0) #By row

array([8, 8, 9])

In [58]:
x.max(axis = 1) #By Col

array([7, 9, 5])

In [59]:
x.cumsum()

array([ 7, 14, 15, 23, 31, 40, 45, 50, 52])

In [60]:
x.mean()

5.777777777777778

In [61]:
np.mean(x)

5.777777777777778

In [62]:
np.median(x)

7.0

Pearson product-moment correlation coefficients

In [63]:
np.corrcoef(x)

array([[ 1., -1.,  1.],
       [-1.,  1., -1.],
       [ 1., -1.,  1.]])

In [64]:
np.std(x)

2.6152449546532934

In [65]:
x.std()

2.6152449546532934

In [66]:
x.var()

6.839506172839506

In [67]:
np.var(x)

6.839506172839506

---

### Sorting

Sort within the array

In [68]:
x

array([[7, 7, 1],
       [8, 8, 9],
       [5, 5, 2]])

In [69]:
x.sort()

In [70]:
x

array([[1, 7, 7],
       [8, 8, 9],
       [2, 5, 5]])

Axis wise sort

In [71]:
x.sort(0)

In [72]:
x

array([[1, 5, 5],
       [2, 7, 7],
       [8, 8, 9]])

---

### Subsetting, Slicing, Indexing

In [73]:
x

array([[1, 5, 5],
       [2, 7, 7],
       [8, 8, 9]])

In [74]:
x[0:1, :]

array([[1, 5, 5]])

In [75]:
x[0]

array([1, 5, 5])

In [76]:
x[0][2]

5

In [77]:
x[:2]

array([[1, 5, 5],
       [2, 7, 7]])

In [78]:
x[:,1] # Column 1

array([5, 7, 8])

In [79]:
x[0,...]

array([1, 5, 5])

In [80]:
x[0,:]

array([1, 5, 5])

In [81]:
x[::-1]

array([[8, 8, 9],
       [2, 7, 7],
       [1, 5, 5]])

In [82]:
x[::-1]

array([[8, 8, 9],
       [2, 7, 7],
       [1, 5, 5]])

Boolean Indexing

In [83]:
x[x<5]

array([1, 2])

In [84]:
x[x == 4]

array([], dtype=int64)

---