# Numpy

In [88]:
import numpy.linalg as la
import numpy as np

In [89]:
np.set_printoptions(precision=3,suppress=True)

---

### Initializing a np array

In [90]:
np.random.rand(3,3)

array([[0.092, 0.58 , 0.233],
       [0.963, 0.886, 0.011],
       [0.128, 0.241, 0.179]])

In [91]:
np.random.randint(10, size = (3,3))


array([[7, 8, 6],
       [2, 6, 9],
       [0, 6, 0]])

In [92]:
np.array([(1,2,3),(4,5,6)])

array([[1, 2, 3],
       [4, 5, 6]])

In [93]:
np.array([1,2,3])

array([1, 2, 3])

Identity Matrix

In [94]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [95]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [96]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

An array of evenly spaced values (number of samples)

In [97]:
np.linspace(0,2,9) 

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

Zero Matrix

In [98]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [99]:
np.empty((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

np.empty , unlike zeros , does not set the array values to zero, and may therefore be marginally faster. On the other hand, it requires the user to manually set all the values in the array, and should be used with caution.

In [100]:
np.full((2,4),7) 

array([[7, 7, 7, 7],
       [7, 7, 7, 7]])

---

### Inspecting Your Array

In [101]:
np.array([1,2,3]).shape

(3,)

In [102]:
np.array([(1,2,3),(4,5,6)]).shape

(2, 3)

In [103]:
np.array([(1,2,3),(4,5,6)]).ndim

2

In [104]:
len(np.array([(1,2,3),(4,5,6)]))

2

In [105]:
np.array([(1,2,3),(4,5,6)]).dtype

dtype('int64')

In [106]:
np.array([(1,2,3),(4,5,6)]).dtype.name

'int64'

In [107]:
np.info(np.array([(1,2,3),(4,5,6)]))

class:  ndarray
shape:  (2, 3)
strides:  (24, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x7f8748e19b00
byteorder:  little
byteswap:  False
type: int64


In [176]:
x = np.random.rand(3,3)
print(x)
print()
print(x.astype(int))

[[0.41  0.849 0.24 ]
 [0.567 0.764 0.055]
 [0.539 0.45  0.482]]

[[0 0 0]
 [0 0 0]
 [0 0 0]]


---

### Matrix Manipulations

Transpose

In [177]:
np.transpose(x)

array([[0.41 , 0.567, 0.539],
       [0.849, 0.764, 0.45 ],
       [0.24 , 0.055, 0.482]])

In [178]:
x.T

array([[0.41 , 0.567, 0.539],
       [0.849, 0.764, 0.45 ],
       [0.24 , 0.055, 0.482]])

Scalar Multiplication

In [110]:
3 * np.identity(3)

array([[3., 0., 0.],
       [0., 3., 0.],
       [0., 0., 3.]])

In [179]:
x.ravel()

array([0.41 , 0.849, 0.24 , 0.567, 0.764, 0.055, 0.539, 0.45 , 0.482])

In [184]:
x.reshape(3,3) # Transpose

array([[0.41 , 0.849, 0.24 ],
       [0.567, 0.764, 0.055],
       [0.539, 0.45 , 0.482]])

In [186]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [188]:
a.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [189]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [213]:
a = a.reshape(3,2)
b = np.array([(6,7),(8,9)])

In [214]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [215]:
b

array([[6, 7],
       [8, 9]])

In [216]:
np.concatenate((a,b)) # Add a tuple

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [217]:
np.vstack((a,b))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [219]:
# np.hstack((a,b))

---

### Matrix Operations

In [112]:
x = np.random.randint(1,10, size = (3,3))
x

array([[4, 5, 5],
       [7, 6, 7],
       [2, 8, 2]])

In [113]:
y = np.random.randint(1,10, size = (3,3))
y

array([[2, 6, 3],
       [2, 8, 2],
       [1, 7, 6]])

In [114]:
np.add(x,y)

array([[ 6, 11,  8],
       [ 9, 14,  9],
       [ 3, 15,  8]])

In [115]:
x + y

array([[ 6, 11,  8],
       [ 9, 14,  9],
       [ 3, 15,  8]])

In [116]:
np.subtract(x,y)

array([[ 2, -1,  2],
       [ 5, -2,  5],
       [ 1,  1, -4]])

In [117]:
x - y

array([[ 2, -1,  2],
       [ 5, -2,  5],
       [ 1,  1, -4]])

In [118]:
np.divide(x,y) #Element-wise

array([[2.   , 0.833, 1.667],
       [3.5  , 0.75 , 3.5  ],
       [2.   , 1.143, 0.333]])

In [119]:
x/y

array([[2.   , 0.833, 1.667],
       [3.5  , 0.75 , 3.5  ],
       [2.   , 1.143, 0.333]])

In [120]:
np.multiply(x,y) #Element-wise

array([[ 8, 30, 15],
       [14, 48, 14],
       [ 2, 56, 12]])

In [121]:
np.exp([1,2,3]) # Natural(e)

array([ 2.718,  7.389, 20.086])

In [122]:
2.718 ** 1, 2.718 ** 2, 2.718 ** 3 

(2.718, 7.387524, 20.079290231999998)

In [123]:
np.sqrt(x)

array([[2.   , 2.236, 2.236],
       [2.646, 2.449, 2.646],
       [1.414, 2.828, 1.414]])

In [124]:
np.sin(x)

array([[-0.757, -0.959, -0.959],
       [ 0.657, -0.279,  0.657],
       [ 0.909,  0.989,  0.909]])

In [125]:
np.log(x) # Element-wise natural logarithm

array([[1.386, 1.609, 1.609],
       [1.946, 1.792, 1.946],
       [0.693, 2.079, 0.693]])

*** * ****
### Dot Product

In [126]:
x.dot(y)

array([[ 23,  99,  52],
       [ 33, 139,  75],
       [ 22,  90,  34]])

---

### Comparisons

In [127]:
x == y

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [128]:
x < y

array([[False,  True, False],
       [False,  True, False],
       [False, False,  True]])

In [129]:
np.array_equal(x, y) 

False

---

### Aggregate Functions

In [130]:
x.sum()

46

In [131]:
x.min()

2

In [132]:
x.max()

8

In [133]:
x.max(axis = 0) #By row

array([7, 8, 7])

In [134]:
x.max(axis = 1) #By Col

array([5, 7, 8])

In [135]:
x.cumsum()

array([ 4,  9, 14, 21, 27, 34, 36, 44, 46])

In [136]:
x.mean()

5.111111111111111

In [137]:
np.mean(x)

5.111111111111111

In [138]:
np.median(x)

5.0

Pearson product-moment correlation coefficients

In [139]:
np.corrcoef(x)

array([[ 1. , -0.5,  0.5],
       [-0.5,  1. , -1. ],
       [ 0.5, -1. ,  1. ]])

In [140]:
np.std(x)

2.0245407953653998

In [141]:
x.std()

2.0245407953653998

In [142]:
x.var()

4.098765432098765

In [143]:
np.var(x)

4.098765432098765

---

### Sorting

Sort within the array

In [144]:
x

array([[4, 5, 5],
       [7, 6, 7],
       [2, 8, 2]])

In [145]:
x.sort()

In [146]:
x

array([[4, 5, 5],
       [6, 7, 7],
       [2, 2, 8]])

Axis wise sort

In [147]:
x.sort(0)

In [148]:
x

array([[2, 2, 5],
       [4, 5, 7],
       [6, 7, 8]])

---

### Subsetting, Slicing, Indexing

In [149]:
x

array([[2, 2, 5],
       [4, 5, 7],
       [6, 7, 8]])

In [162]:
x[0:1, :]

array([[2, 2, 5]])

In [163]:
x[0]

array([2, 2, 5])

In [164]:
x[0][2]

5

In [154]:
x[:2]

array([[2, 2, 5],
       [4, 5, 7]])

In [160]:
x[:,1] # Column 1

array([2, 5, 7])

In [165]:
x[0,...]

array([2, 2, 5])

In [168]:
x[0,:]

array([2, 2, 5])

In [169]:
x[::-1]

array([[6, 7, 8],
       [4, 5, 7],
       [2, 2, 5]])

In [172]:
x[::-1]

array([[6, 7, 8],
       [4, 5, 7],
       [2, 2, 5]])

Boolean Indexing

In [174]:
x[x<5]

array([2, 2, 4])

In [175]:
x[x == 4]

array([4])

---